### ISSUE TITLE
Notetool import error

### ISSUE THREAD

**Issue by JIACHENG135** [notechats/notedrive#1]
ImportError: cannot import name 'log' from 'notetool'
`from notedrive.baidu.drive import BaiDuDrive`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ljc14\AppData\Local\Programs\Python\Python37\lib\site-packages\notedrive\baidu\drive.py", line 11, in <module>
    from notetool import log
ImportError: cannot import name 'log' from 'notetool' `

**Comment by 1007530194** [comment]
不好意思，没注意到

你可以用下面的方式再重新安装下
pip install git+https://github.com/notechats/notedrive.git
pip install git+https://github.com/notechats/notetool.git
